---
- name: Install and start Nginx on an Azure virtual machine
  hosts: all
  become: yes
  tasks:

  - name: mise a jour
    apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes

  - name: installation de "Nginx"
    apt:
      name: nginx
      state: present
  
  - name: permission sur le repertoire /var/www/html  
    file:
      path: /var/www/html
      mode: '0755'
  
  - name: recuperation du site
    get_url:
      url: https://raw.githubusercontent.com/Pierre-Chesne/AzureDevOps-Ansible-Web-VM/master/SiteWeb.zip
      dest: /home/pierrc/SiteWeb.zip
  
  - name: installation Unzip
    apt:
      name: unzip
      update_cache: yes
      state: present
           
  - name: unzip le site
    unarchive:
      src: /home/pierrc/SiteWeb.zip
      dest: /home/pierrc/
      remote_src: yes

  - name: copy le site
    copy:
      src: /home/pierrc/SiteWeb/
      dest: /var/www/html/
      remote_src: yes